//----------------DBMS---------

// DATA STORAGE  -----

// TYPES OF DATABASE --- 1. SQL, 2. NOSQL

//SQL -- DATA KO AK ROOOP ME RAKHANA ( TABLES ).

// NOSQL -- YAHA PE DATA OBJECT KE FORM ME HOTA HAI {OBJECTS }. YE BHI AK CONCEPT HAI.

//NOSQL -- YE AK CONCEPT HAI ( YAHA PE DATA OBJECT KE FORME ME RAKHA JAYEGA).

// MONODB -- YE AK REAL DATABSE HAI JO KI DONO KE CONCEPT PE KAM KARTA HAI.

//WHY MONGODB -- TO STORE DATA FROM THE SERVER.

//BACKEND -- YAHA PE TWO SERVER HOTA HAI ( APPLICATION / DATABASE ).

//APPLICATION SERVER -- SAB KUCHH KARN AONLY DATA KA KAM CHODE KE.

// DATABSE SERVER -- YAHA PE DATA STORE HOTA HAI FRONTENT SE JO SEND HOTA HAI BACKEND ME.

//DATABASE > COLLECTION > DOCUMENT > CODE.

//MONGOOSE.CONNECT  >>  DATABASE CREATE.
// MODEL CREATE  >> COLLECTION 
// CREATE CODE >> DOCUMENT.